name: Pretronic.DiscordBot image

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login docker-registry.pretronic.net -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin
    - name: Build image
      run: docker build . --file Dockerfile -t docker-registry.pretronic.net/pretronic/pretronic-discord-bot:${{ github.sha }} -t docker-registry.pretronic.net/pretronic/pretronic-discord-bot:latest -t docker-registry.pretronic.net/pretronic/pretronic-discord-bot:latest-master
    - name: Push image
      run: docker push --all-tags docker-registry.pretronic.net/pretronic/pretronic-discord-bot
